spring.application.name=survey-builder
server.port=${PORT:8080}

# Database Configurations (Adapts automatically based on environment variables)
spring.datasource.url=${JDBC_DATABASE_URL:jdbc:h2:file:./data/surveydb;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.driverClassName=${JDBC_DATABASE_DRIVER:org.h2.Driver}
spring.datasource.username=${JDBC_DATABASE_USERNAME:sa}
spring.datasource.password=${JDBC_DATABASE_PASSWORD:}
spring.jpa.database-platform=${JPA_DIALECT:org.hibernate.dialect.H2Dialect}

# Enable H2 Database Console access
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# JPA/Hibernate DDL auto schema updates
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
